buildscript {
    ext.kotlin_version = '1.9.22'
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}

subprojects { project ->
    def configureVerify = {
        if (project.hasProperty('android')) {
            project.tasks.matching { it.name.contains("verify") && it.name.contains("ReleaseResources") }.configureEach {
                enabled = false
            }
        }
    }
    if (project.state.executed) {
        configureVerify()
    } else {
        project.afterEvaluate {
            configureVerify()
        }
    }
}
